### ISSUE TITLE
Hardcoded "caption" class is still in build file

### ISSUE THREAD

**Issue by Haargeeel** [Spyna/react-svg-radar-chart#4]
Hey Lorenzo,

I see your last commit is to remove the hardcoded "caption" class but the latest version on _npm_ still has it in the `build/index.js` file. Could you republish it?

Other than that. Great, easy to use library. Thanks

**Comment by Spyna** [comment]
Thank you for noticing me this, I just republished it. You can update to version 1.0.6. 

The default class of the *caption elements* is `caption`, so you have to override the options in order to change it. 

These are the default options: 

```JavaScript
const defaultOptions = {
  size: 300,
  axes: true, // show axes?
  scales: 3, // show scale circles?
  captions: true, // show captions?
  zoomDistance: 1.2, // where on the axes are the captions?
  smoothing: noSmoothing, // shape smoothing function
  captionMargin: 10,
  axisProps: () => ({ className: 'axis' }),
  scaleProps: () => ({ className: 'scale', fill: 'none' }),
  shapeProps: () => ({ className: 'shape' }),
  captionProps: () => ({
    className: 'caption',
    textAnchor: 'middle',
    fontSize: 10,
    fontFamily: 'sans-serif'
  })
};
```
the entry `captionProps` is a function that will be applied when rendering the `caption` elements. The result of this function will be applied as `props` to the `<text>` element of the `svg`. 

To override the class for caption you have to do:

```JavaScript
const myCustomOptions = {
  captionProps: () => ({
    className: 'ANOTHER-FANCY-CLASS',
    fontSize: 20,
  })
};

<RadarChart ... options={myCustomOptions} />
```
the result will be 

```JavaScript
<text ... class="ANOTHER-FANCY-CLASS" font-size="20" font-family="sans-serif">...</text>
```
